# -------------------------------- Qt --------------------------------
if(BUILD_QT5)
  set(_QT_V 5)
elseif(BUILD_QT6)
  set(_QT_V 6)
endif()
find_package(Qt${_QT_V}Core REQUIRED)
set(CMAKE_AUTOMOC TRUE)

# For FreeCAD 0.20, pegged to Ubuntu 18.04 LTS:
if(${Qt${_QT_V}Core_VERSION} VERSION_LESS "5.9")
    message (FATAL_ERROR "FreeCAD v0.20 requires Qt5 5.9 or later")
endif()
find_package(Qt${_QT_V}Network REQUIRED)
#find_package(Qt5Xml REQUIRED)
#find_package(Qt5XmlPatterns REQUIRED)
find_package(Qt${_QT_V}Concurrent REQUIRED)
if(BUILD_GUI)
    find_package(Qt${_QT_V}Widgets REQUIRED)
    find_package(Qt${_QT_V}PrintSupport REQUIRED)
    find_package(Qt${_QT_V}OpenGL REQUIRED)
    find_package(Qt${_QT_V}Svg REQUIRED)
    find_package(Qt${_QT_V}UiTools REQUIRED)
    if (BUILD_WEB)
        if (${FREECAD_USE_QTWEBMODULE} MATCHES "Qt Webkit")
            find_package(Qt${_QT_V}WebKitWidgets REQUIRED)
        elseif(${FREECAD_USE_QTWEBMODULE} MATCHES "Qt WebEngine")
            find_package(Qt${_QT_V}WebEngineWidgets REQUIRED)
        else() # Automatic
            find_package(Qt${_QT_V}WebEngineWidgets QUIET)
            if(NOT Qt${_QT_V}WebEngineWidgets_FOUND)
                find_package(Qt${_QT_V}WebEngineWidgets REQUIRED)
            endif()
        endif()
    endif()
    if(MSVC)
      find_package(Qt5WinExtras QUIET)
    endif()
endif(BUILD_GUI)
