# -------------------------------- Qt --------------------------------

find_package(Qt6Core REQUIRED)
set(CMAKE_AUTOMOC TRUE)

# For FreeCAD 0.20, pegged to Ubuntu 18.04 LTS:
if(${Qt6Core_VERSION} VERSION_LESS "5.9")
    message (FATAL_ERROR "FreeCAD v0.20 requires Qt5 5.9 or later")
endif()
find_package(Qt6Network REQUIRED)
#find_package(Qt5Xml REQUIRED)
#find_package(Qt5XmlPatterns REQUIRED)
find_package(Qt6Concurrent REQUIRED)
if(BUILD_GUI)
    find_package(Qt6Widgets REQUIRED)
    find_package(Qt6PrintSupport REQUIRED)
    find_package(Qt6OpenGL REQUIRED)
    find_package(Qt6Svg REQUIRED)
    find_package(Qt6UiTools REQUIRED)
    # if (BUILD_WEB)
    #     if (${FREECAD_USE_QTWEBMODULE} MATCHES "Qt Webkit")
    #         find_package(Qt5WebKitWidgets REQUIRED)
    #     elseif(${FREECAD_USE_QTWEBMODULE} MATCHES "Qt WebEngine")
    #         find_package(Qt5WebEngineWidgets REQUIRED)
    #     else() # Automatic
    #         find_package(Qt5WebEngineWidgets QUIET)
    #         if(NOT Qt5WebEngineWidgets_FOUND)
    #             find_package(Qt5WebKitWidgets REQUIRED)
    #         endif()
    #     endif()
    # endif()
    if(MSVC)
      find_package(Qt5WinExtras QUIET)
    endif()
endif(BUILD_GUI)
